version: 2

python:
  version: "3"
  install:
  - requirements: requirements.txt

# Additional (downloadable) formats of the documentation to be built, apart
# from the default HTML.
formats:
- htmlzip
