[tool.codespell]
# See: https://github.com/codespell-project/codespell#using-a-config-file
# In case of a false positive, add the problematic word, in all lowercase, to a comma-separated list here:
ignore-words-list = ','
skip = './.git,'

[tool.isort]
profile = "black"
