package:
  name: pyinstrument
  version: "0.13.1"
 
source:
  git_rev: 0.13.1
  git_url: https://github.com/joerick/pyinstrument.git
 
requirements:
  build:
    - python
    - setuptools
  run:
    - python
 
test:
  imports:
    - pyinstrument
 
about:
  home: https://github.com/joerick/pyinstrument
  license: BSD
